### PR TITLE
Allow arc5gl user to be configured via ~/.arcgl_user file

### PR DESCRIPTION
**Pull request by taldcroft**
This makes Ska.arc5gl more flexible for Ska processing needs.

## Functional testing

As user `aca` was able to get a recent event file using `Ska.arc5gl` from the archive.

### CODE REVIEW

**Comment by jeanconn** [comment]
Makes sense, but what is the application?

**Comment by jeanconn** [comment]
I think we probably want to just do this.

**Comment by taldcroft** [comment]
I added a description of the testing. I think this is ready to go.

**Comment by taldcroft** [comment]
With this we can do eng_archive and astromon processing as `aca`.

**Review by jeanconn — APPROVED** [review]

**Pull request merged**
